name: Generate Stat JSONs

on:
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy openpyxl xlrd

      - name: Run stat generator
        run: python scripts/stat_json_generator.py

      - name: List output files
        run: ls -lR data/

      - name: Commit and push JSON
        run: |
          git config --global user.name 'auto-updater'
          git config --global user.email 'auto@updater.com'
          git add data/stats/
          git commit -m "Auto-update stats"
          git push
        continue-on-error: true
