name: Generate Stat JSONs

on:
  push:
    paths:
      - 'data/1999 Replay.xlsx'
      - 'scripts/generate_stats.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy openpyxl

      - name: Run stat generator
        run: python scripts/generate_stats.py

      - name: Commit and push updated JSON files
        run: |
          git config --global user.name 'auto-updater'
          git config --global user.email 'auto@updater.com'
          git add data/stats/
          git add data/boxscores/
          git commit -m "Auto-update generated JSON files"
          git push
        continue-on-error: true

      - name: Trigger Vercel Deployment
        run: curl -X POST 'https://api.vercel.com/v1/integrations/deploy/prj_KVc1MRftUPAE4iQBGP6jSryRPfcz/IePnWdQdej'
