name: Generate Stat and Schedule JSONs

on:
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy openpyxl xlrd

      - name: Run stat generator
        run: python scripts/stat_json_generator.py

      - name: Run schedule and standings generator
        run: python scripts/schedule_and_standings_generator.py

      - name: Commit and push updated JSON files
        run: |
          git config --global user.name 'auto-updater'
          git config --global user.email 'auto@updater.com'
          git add data/stats/*.json
          git commit -m "Auto-update stats, schedule, and standings from Excel"
          git push

      - name: Trigger Vercel Deployment
        run: curl -X POST 'https://api.vercel.com/v1/integrations/deploy/prj_KVc1MRftUPAE4iQBGP6jSryRPfcz/IePnWdQdej'
