name: Generate Stat JSONs

on:
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy openpyxl xlrd

      - name: Run stat generator
        run: python scripts/stat_json_generator.py

      - name: Copy players_combined.json to public folder
        run: |
          mkdir -p public/data/stats
          cp data/stats/players_combined.json public/data/stats/players_combined.json

      - name: Commit and push updated JSON files
        run: |
          git config --global user.name 'auto-updater'
          git config --global user.email 'auto@updater.com'
          git add data/stats/
          git add data/standings.json
          git add data/schedule.json
          git add public/data/stats/players_combined.json
          git commit -m "Auto-update stats and push player JSON to public folder"
          git push

      - name: Trigger Vercel Deployment
        run: curl -X POST 'https://api.vercel.com/v1/integrations/deploy/prj_KVc1MRftUPAE4iQBGP6jSryRPfcz/IePnWdQdej'
